# Calculates required commits for today based on image.text in repo and commits specified times
name: Draw

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch: {}

permissions:
  contents: write
  
jobs:
  draw:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - id: gen_commit_count
      run: python main.py

    - run: |
        echo "## $(cat commit_count) commits expected today" >> $GITHUB_STEP_SUMMARY

    - name: Commit changes
      run: |
        git config --global user.name ${{ secrets.USERNAME }}
        git config --global user.email ${{ secrets.EMAIL }}
        
        git remote set-url origin https://${{ secrets.USERNAME }}:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}
        seq $(cat commit_count) | xargs -I{} sh -c "date -Ins > bump && git add -v bump && git commit -m '[AUTOMATED] Bump' -- bump && sleep 15"
        
        if ! git diff --quiet HEAD origin/main -- bump; then
          git push
        fi
